### ISSUE TITLE
When the script ends, the channel is disabled 

### ISSUE THREAD

**Issue by dbrb2** [tspspi/pyfy6900#1]
Not sure if this is by design - but this seems to work, except that when the python script ends, the channels both disable themselves: 

```
import numpy as np

from pyfy6900 import fy6900
from labdevices.functiongenerator import FunctionGeneratorWaveform
from time import sleep


with fy6900.FY6900Serial("/dev/ttyUSB0", debug = True) as fg:

    fg.set_channel_waveform(0, FunctionGeneratorWaveform.CMOS)
    fg.set_channel_frequency(0, 100)
    fg.set_channel_offset(0, 0)
    fg.set_channel_amplitude(0, 3.3)
    fg.set_channel_enabled(0, True)
    fg.set_channel_enabled(1, True)
    #sleep(60)
```

Without sleep, the channel disables immediately 
With sleep, it disables after 60 seconds 

I can see this is due to: 

self._off()

called when the script ends. It would be amazing if it were possible to not call this!

**Comment by tspspi** [comment]
Yes currently this is by design. Whenever the object gets released the device is put in a "safe state" (i.e. channels turned off). If there are scenarios where this would be a problem I could add a flag to make this behaviour optional.

**Comment by tspspi** [comment]
Just pushed a new variant (currently untested) that now has a "shutdownOnExit" flag that should be useable on the constructor to prevent this:

```
import numpy as np

from pyfy6900 import fy6900
from labdevices.functiongenerator import FunctionGeneratorWaveform
from time import sleep


with fy6900.FY6900Serial("/dev/ttyUSB0", debug = True, shutdownOnExit = False) as fg:

    fg.set_channel_waveform(0, FunctionGeneratorWaveform.CMOS)
    fg.set_channel_frequency(0, 100)
    fg.set_channel_offset(0, 0)
    fg.set_channel_amplitude(0, 3.3)
    fg.set_channel_enabled(0, True)
    fg.set_channel_enabled(1, True)
    #sleep(60)
```

**Comment by dbrb2** [comment]
Thanks! For now I've changed it locally.
Interestingly,  we also have a 6800 unit

I tried a different library too, which worked fine with the 6800 but not
the 6900, so I think the API must have subtly changed between models

Thanks for the implementation!!

**Comment by tspspi** [comment]
I admit I have not invested much time into implementing more features over the time (since I actually usually use devices like the Rigol DG832 or the Siglent SDG1032X which is a little bit more expensive but even works with Ethernet which makes life much easier (had much trouble with the 6900 due to the used serial to USB port so I actually have to use the TTL pins on the back to circumvent the broken CH340 that just does not work on FreeBSD - a commonly known thing - so I actually utilize an external CP2021N to control the FY6900). I've never ever taken a look at the 6800 though.

Do you have any source for protocols for the 6800? (I try to extend my [pylabdevs](https://github.com/tspspi/pylabdevs) collection all the time whenever I encounter devices that are easy to add)

**Comment by dbrb2** [comment]
I found the difference: 

It looks like, although my protocol document for the 6900 says that frequency is passed in as uHz, for the 6900 it is in fact passed in as Hz with a decimal place (which is what you implement I think) 

The 6800 on the other hand _does_ expect frequency in uHz 
Since the 6800 was expecting uHz, the value passed in in uHz maxed it out

All good now!
